#!/usr/bin/python

import subprocess as sp

def get_instance_metadata():
  lines = sp.check_output("ec2metadata").split("\n")
  pairs = [[x.strip() for x in line.split(":")] for line in lines]
  pairs = [x for x in pairs if len(x)==2]
  return dict(pairs)

def get_hostname():
  metadata = get_instance_metadata()
  return metadata['public-hostname']

if __name__=='__main__':
  hostname = get_hostname()

  # start up cluster worker
  pp = sp.Popen(["java","-jar", "./build/libs/otpa-cluster-all.jar", hostname])

  pp.wait()
