#!/usr/bin/python

import subprocess as sp
import sys

def get_instance_metadata():
  lines = sp.check_output("ec2metadata").split("\n")
  pairs = [[x.strip() for x in line.split(":")] for line in lines]
  pairs = [x for x in pairs if len(x)==2]
  return dict(pairs)

def get_hostname():
  metadata = get_instance_metadata()
  return metadata['public-hostname']

def register_self(hostname):

  if len(sys.argv)<2:
    exit("missing master hostname argument")

  master_hostname = sys.argv[1]

  url = "http://%s/addworker/?path=MySystem@%s:2553/user/manager"%(master_hostname, hostname)

  import urllib

  print "registering worker using: %s"%url
  fp = urllib.urlopen( url )
  print fp.read()

if __name__=='__main__':
  hostname = get_hostname()

  wrk = sp.Popen(["java","-jar", "-Dconfig.resource=worker.conf", "./otpa-cluster/build/libs/otpa-cluster-all.jar", hostname],stdout=sp.PIPE)
  while True:
    line = wrk.stdout.readline()
    print line,
    if line.split()[:2]==["starting","manager"]:
      break

  import time
  time.sleep(3)

  try:	
    register_self(hostname)
  except Exception, ex:
    wrk.terminate()
    raise ex

  while True:
    line = wrk.stdout.readline()
    if len(line)==0:
      time.sleep(0.1)
    else:
      print line,
